/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.4.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.configuration;

import com.ftm.vcp.bootexamples.infrastructure.driving.rest.api.CartApi;

import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

public abstract class HttpInterfacesAbstractConfigurator {

    private final WebClient webClient;

    public HttpInterfacesAbstractConfigurator(final WebClient webClient) {
        this.webClient = webClient;
    }

    @Bean(name = "org.openapitools.configuration.HttpInterfacesAbstractConfigurator.cart")
    CartApi cartHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(WebClientAdapter.create(webClient)).build();
        return factory.createClient(CartApi.class);
    }


}
