spring:
  datasource:
    name: foo
    generate-unique-name: false
  devtools:
    restart:
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    name: postgres
#    password: postgres
#    username: postgres
  sql:
    init:
      continue-on-error: true
      mode: always
logging:
  level:
    org:
      springframework:
        boot:
          devtools: debug
